export let lista = [
    {
        "Nombre": "Fideos",
        "Marca": "Lucchetti",
        "Categoría": "Pastas",
        "Tipo": "Codito",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/157/846/products/diseno-sin-titulo-2022-05-12t102428-9141-f88a149070c89a1fff16523619861162-1024-1024.png",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "1",
        "Fecha": "17/08/2024",
        "Vence": "11/07/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "1800",
        "_16": "",
        "_17": "153195"
    },
    {
        "Nombre": "Fideos",
        "Marca": "Lucchetti",
        "Categoría": "Pastas",
        "Tipo": "Tirabuzón",
        "Imagen": "https://atencion24.ar/wp-content/uploads/2023/09/199a82aa-bd39-4853-8297-e0d3a701e277.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "2",
        "Fecha": "17-ago",
        "Vence": "22/06/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Favorita",
        "Categoría": "Pastas",
        "Tipo": "Codito",
        "Imagen": "https://modomarketar.vteximg.com.br/arquivos/ids/171422/Fideos-Favorita-Codito-Hierro-X-500-G-1-41.jpg?v=638604561677670000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1100",
        "Venta": "1650",
        "Cantidad": "2",
        "Fecha": "17/08/2024",
        "Vence": "04/12/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3300",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Knorr",
        "Categoría": "Pastas",
        "Tipo": "Spaghetti",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/321949/Fideos-Knorr-Spaghetti-500-Gr-_2.jpg?v=638599537728700000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "1",
        "Fecha": "17/08/2024",
        "Vence": "16/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Dos Anclas",
        "Categoría": "Sal",
        "Tipo": "Fina",
        "Imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/188583/Sal-Fina-Dos-Anclas-X500gr-Sal-Fina-Dos-Anclas-Trilaminado-500-Gr-1-24926.jpg?v=636383496216030000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "",
        "Lote": "04/08/2023",
        "Estado": "Sin info",
        "Valores": "4200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Celusal",
        "Categoría": "Sal",
        "Tipo": "Fina",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/193/620/products/1631-b3f7f78d649af51a2f16074500575515-480-0.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "3",
        "Fecha": "",
        "Vence": "15/07/2027",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "5400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Celusal",
        "Categoría": "Sal",
        "Tipo": "Gruesa",
        "Imagen": "https://arjosimarprod.vteximg.com.br/arquivos/ids/158813-1000-1000/Sal-Gruesa-Celusal-Paquete-1-kg-1-1768.jpg?v=637414118609900000",
        "Descripción": "",
        "Tamaño": "Grande",
        "Peso": "1000g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "26/10/2027",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "5400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Dos Anclas",
        "Categoría": "Sal",
        "Tipo": "Gruesa",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/545896/7792900613017_02.jpg?v=638582149188200000",
        "Descripción": "",
        "Tamaño": "Grande",
        "Peso": "1000g",
        "Costo": "1700",
        "Venta": "2550",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "12/01/2023",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "2550",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochuelo",
        "Marca": "Emeth",
        "Categoría": "Premezclas",
        "Tipo": "Dulce de Leche",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/410314/7791113005466_02.jpg?v=638345480717300000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "450g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "01/10/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "2700",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Categoría": "Premezclas",
        "Tipo": "Ananá",
        "Imagen": "https://www.almacenencasa.com.ar/500-thickbox_default/gelatina-anana-vitaminizado-6-70-grs-emeth.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "nov-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "1560",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Categoría": "Premezclas",
        "Tipo": "Cereza",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/330352/Gelatina-Cereza-Vitaminizada-Emeth-70-GR-_1.jpg?v=638599648147970000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3120",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Categoría": "Premezclas",
        "Tipo": "Frambuesa",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/330349/Gelatina-Frambuesa-Con-Vitamina-Z-Emeth-70-Gr-_1.jpg?v=638599648096800000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "3",
        "Fecha": "",
        "Vence": "feb-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "4680",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Categoría": "Premezclas",
        "Tipo": "Naranja",
        "Imagen": "https://www.almacenencasa.com.ar/498-thickbox_default/gelatina-naranja-vitaminizado-6-70-grs-emeth.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "4",
        "Fecha": "",
        "Vence": "ene-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "6240",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Salvador",
        "Categoría": "Azúcar",
        "Tipo": "A",
        "Imagen": "https://www.consumosbasicos.com.ar/images/000000000000051983731519.jpeg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "1100",
        "Venta": "1650",
        "Cantidad": "4",
        "Fecha": "",
        "Vence": "01/12/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "6600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Marolio",
        "Categoría": "Azúcar",
        "Tipo": "A",
        "Imagen": "https://http2.mlstatic.com/D_625068-MLA51742912883_092022-C.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "13/08/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "1950",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Azucel",
        "Categoría": "Azúcar",
        "Tipo": "A ",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/325793/Azucar-Azucel-Comun-tipo-A-1-Kg-_1.jpg?v=638599585785670000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "31/12/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "1800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Edulcorante",
        "Marca": "Hileret ",
        "Categoría": "Edulcorantes",
        "Tipo": "Mate",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/200470/7790490998002_02.jpg?v=637550326133900000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "200ml",
        "Costo": "2100",
        "Venta": "3150",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "feb-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "6300",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "Taragüí",
        "Categoría": "Infusiones",
        "Tipo": "En saquitos",
        "Imagen": "https://modomarketar.vteximg.com.br/arquivos/ids/161974/Te-Taragui-S-ensobrar-X-25-Saq-1-6608.jpg?v=637879777592570000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "sep-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "Taragüí",
        "Categoría": "Infusiones",
        "Tipo": "En saquitos",
        "Imagen": "https://modomarketar.vteximg.com.br/arquivos/ids/161974/Te-Taragui-S-ensobrar-X-25-Saq-1-6608.jpg?v=637879777592570000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "sep-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "1800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "La Virginia",
        "Categoría": "Infusiones",
        "Tipo": "En saquitos",
        "Imagen": "https://www.lavirginia.com.ar/wp-content/uploads/2022/01/7790150211908_02-scaled.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "20/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "4200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "Rosamonte",
        "Categoría": "Infusiones",
        "Tipo": "En saquitos",
        "Imagen": "https://cordoba.parodisrl.com.ar/47211/te-rosamonte-25-saq-s-sobre.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1500",
        "Venta": "2250",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "10/08/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "2250",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Mate cocido",
        "Marca": "Amanda",
        "Categoría": "Infusiones",
        "Tipo": "En saquitos",
        "Imagen": "https://acdn.mitiendanube.com/stores/043/230/products/mate-cocido-tradicional_3_c1-86cb7d01479528ff5a16109958803054-1024-1024.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1500",
        "Venta": "2250",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "03/04/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2250",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Orégano",
        "Marca": "Las Elviras",
        "Categoría": "Condimentos",
        "Tipo": "",
        "Imagen": "https://especiaslaselviras.com/wp-content/uploads/2022/09/Oregano.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Ajo en polvo",
        "Marca": "Las Elviras",
        "Categoría": "Condimentos",
        "Tipo": "",
        "Imagen": "https://especiaslaselviras.com/wp-content/uploads/2022/09/Ajo-en-polvo.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo en polvo",
        "Marca": "Tang",
        "Categoría": "Jugos",
        "Tipo": "Naranja Mango",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/435018/7622201735371_E01.jpg?v=638400547833970000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "270",
        "Venta": "405",
        "Cantidad": "6",
        "Fecha": "",
        "Vence": "25/09/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "2430",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo en polvo",
        "Marca": "Tang",
        "Categoría": "Jugos",
        "Tipo": "Naranja ",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/181368/Jugo-En-Polvo-Naranja-Durazno-Tang-15-Gr-1-15195.jpg?v=638403465881630000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "270",
        "Venta": "405",
        "Cantidad": "10",
        "Fecha": "",
        "Vence": "17/10/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "4050",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo en polvo",
        "Marca": "Clight",
        "Categoría": "Jugos",
        "Tipo": "Naranja Dulce",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/322612/Jugo-En-Polvo-Clight-Naranja-Dulce-75-Gr-_1.jpg?v=638599545927670000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "270",
        "Venta": "405",
        "Cantidad": "7",
        "Fecha": "",
        "Vence": "10/12/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2835",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo en polvo",
        "Marca": "Clight",
        "Categoría": "Jugos",
        "Tipo": "Pomelo",
        "Imagen": "https://elnenearg.vtexassets.com/arquivos/ids/166087-800-auto?v=638104413709800000&width=800&height=auto&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "280",
        "Venta": "420",
        "Cantidad": "5",
        "Fecha": "",
        "Vence": "12/11/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2100",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Cachamate",
        "Categoría": "Yerba",
        "Tipo": "Naranja",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/349845/7792280000285_01.jpg?v=638242443160200000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2200",
        "Venta": "3300",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3300",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Amanda",
        "Categoría": "Yerba",
        "Tipo": "Campo",
        "Imagen": "https://lh3.googleusercontent.com/pw/AP1GczNALogRzd3RPPnh9q6p7NvFk3qmkvA0ASo_0RVHbdmIvnSd0VGr8gvaS-dNpqlgtZ82o5FUVLgB9qWN83ApJhZYAS0iR9n3Yvq-7unfRwEZclS02HLKDWyv6BXPVZfnvqZhsa9cFi81tqQoGi7_wT8=w492-h680-s-no-gm",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2800",
        "Venta": "4200",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "21/07/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "4200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Amanda",
        "Categoría": "Yerba",
        "Tipo": "Tradicional",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_832425-MLA48945377120_012022-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "250g",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "04/05/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Salus",
        "Categoría": "Yerba",
        "Tipo": "Suave",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_694299-MLU78227074971_082024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2350",
        "Venta": "3525",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "27/03/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "3525",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Nobleza Gaucha",
        "Categoría": "Yerba",
        "Tipo": "Selección",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/206379/7790070507273_01.jpg?v=637611768560100000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2100",
        "Venta": "3150",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "20/07/2023",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "6300",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Cruz de Malta",
        "Categoría": "Yerba",
        "Tipo": "Tradicional, libre de gluten ",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_837342-MLA71671213585_092023-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2100",
        "Venta": "3150",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "08/03/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "6300",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Puré de tomates",
        "Marca": "S&P",
        "Categoría": "Conservas",
        "Tipo": "",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101971.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "520g",
        "Costo": "750",
        "Venta": "1125",
        "Cantidad": "4",
        "Fecha": "",
        "Vence": "nov-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "4500",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pulpa de tomate",
        "Marca": "Marolio",
        "Categoría": "Conservas",
        "Tipo": "",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_949300-MLA76508136660_052024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "520g",
        "Costo": "990",
        "Venta": "1485",
        "Cantidad": "3",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "4455",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Tomate triturado",
        "Marca": "S&P",
        "Categoría": "Conservas",
        "Tipo": "",
        "Imagen": "https://imagedelivery.net/olI9wp0b6luWFB9nPfnqjQ/res/abillionveg/image/upload/lgpu0e3ms7p6d7vrinfr/1598114874.jpg/public",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "970g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "27/04/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sardinas",
        "Marca": "Marbella",
        "Categoría": "Conservas",
        "Tipo": "En aceite",
        "Imagen": "https://elnenearg.vtexassets.com/arquivos/ids/165328/SARDINAS-MARBELLA-ACEITE-160GR-1-11301.jpg?v=638076657904300000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "160g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "26/07/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2700",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Arroz",
        "Marca": "Dos Hermanos",
        "Categoría": "Arroz",
        "Tipo": "Parboil",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/165472/ARROZ-DOS-HERMANOS-PARBOIL-1-7769.jpg?v=637665502412430000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "2600",
        "Venta": "3900",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "28/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Picadillo ",
        "Marca": "S&P",
        "Categoría": "Conservas",
        "Tipo": "Carne",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101930.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "90g",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "3",
        "Fecha": "",
        "Vence": "21/09/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Paté",
        "Marca": "S&P",
        "Categoría": "Conservas",
        "Tipo": "Foie",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101929.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "90g",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "22/07/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "2400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Atún",
        "Marca": "Bulnez",
        "Categoría": "Conservas",
        "Tipo": "Natural",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/542300/7791720003886_01.jpg?v=638568427419270000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "120g",
        "Costo": "2800",
        "Venta": "4200",
        "Cantidad": "1",
        "Fecha": "",
        "Vence": "13/12/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "4200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pasta Dental",
        "Marca": "Colgate",
        "Categoría": "Higiene",
        "Tipo": "Familiar",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_20871cb36c5245b48bc9fa39978763c7_637592749684913593_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "70g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "La Providencia",
        "Categoría": "Pastas",
        "Tipo": "Tagliatelle",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/178866/7798141971084_02.jpg?v=637468580608230000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Máquina de afeitar",
        "Marca": "Gillette",
        "Categoría": "Higiene",
        "Tipo": "Triple (2 unids)",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/165/255/products/gillette-prestobarba-3-comfortgel-x2-maquinas-dc16df04d144540d1c17151824477588-1024-1024.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "6500",
        "Venta": "9750",
        "Cantidad": "2",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pasta Dental",
        "Marca": "Odol",
        "Categoría": "Higiene",
        "Tipo": "Doble Protección",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_664727-MLU71000746978_082023-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3500",
        "Venta": "5250",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "Fuerza y brillo",
        "Imagen": "https://assets.unileversolutions.com/v1/88717149.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "Hidratación y frizz control",
        "Imagen": "https://assets.unileversolutions.com/v1/92204219.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "Regeneración y luminosidad",
        "Imagen": "https://assets.unileversolutions.com/v1/92203503.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "Restauración y brillo",
        "Imagen": "https://assets.unileversolutions.com/v1/90142454.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "Rizos definidos",
        "Imagen": "https://assets.unileversolutions.com/v1/88720623.png?im=AspectCrop=(985,985);Resize=(985,985)",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Argentino",
        "Categoría": "Limpieza",
        "Tipo": "",
        "Imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/762004-800-600?v=638060457671000000&width=800&height=600&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3000",
        "Venta": "4500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Argentino",
        "Categoría": "Limpieza",
        "Tipo": "",
        "Imagen": "https://soysuper.com.ar/uploads/1565873489_MQ==.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1500",
        "Venta": "2250",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Villa Iris",
        "Categoría": "Limpieza",
        "Tipo": "",
        "Imagen": "https://distriflash.com.ar/wp-content/uploads/2018/11/1782-Jabon-blanco-V-I.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2000",
        "Venta": "3000",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón de Tocador",
        "Marca": "Rexona",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_c0662ee45c01441ba2e602f817c3c6b8_638189398812017116_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Máquina de afeitar",
        "Marca": "Gillette",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://farmaciaslider.pe/my-assets/image/product/e7f4c860710f7df44fc069a77f12cb25.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Toallas femeninas",
        "Marca": "Kotex",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://media03.farmaciaslider.com.ar/33798-thickbox_default/kotex-esencial-con-alas-toallas-higienicas-normal-x-8.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Detergente en barra",
        "Marca": "Villa Iris",
        "Categoría": "Limpieza",
        "Tipo": "",
        "Imagen": "https://dcdn.mitiendanube.com/stores/001/108/127/products/villa-iris-datergente-en-barra1-8e6fd721804488516c16664448613744-640-0.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3700",
        "Venta": "5550",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_602605-MLA74792670662_032024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://www.farmaciassanchezantoniolli.com.ar/455-medium_default/shampoo-sedal-restauracion-instantanea-10ml.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_e180d3f5e90249c69e151b6b8fb92173_638502698936840708_0_m.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Protectores Diarios",
        "Marca": "Doncella",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_a1bf9fedcee64fd1bc1800df1f66cd0a_638599170607307417_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Protectores Diarios",
        "Marca": "Doncella",
        "Categoría": "Higiene",
        "Tipo": "",
        "Imagen": "https://www.centraloeste.com.ar/media/catalog/product/cache/ddb703dc084a33c8cde56cf551816b8e/7/7/7790940233264_-_protector_x_20_anatomico_con_deo_x_20.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    }
]