export let lista = [
    {
        "Nombre": "Aceite",
        "Marca": "Cañuelas",
        "Tipo": "Girasol",
        "Categoría": "Aceite",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/309841/Aceite-de-Girasol-Ca%C3%B1uelas-15-Lts-_1.jpg?v=638599363202730000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2660",
        "Venta": "3990",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": "1074240"
    },
    {
        "Nombre": "Agua Mineral",
        "Marca": "Villa Manaos",
        "Tipo": "Bidón 6l",
        "Categoría": "Agua Mineral",
        "Imagen": "https://distribuidorabelgrano.com/wp-content/uploads/2020/11/bidon-manaos-e1604442066608-600x640.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1320",
        "Venta": "1980",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Arroz",
        "Marca": "Dos Hermanos",
        "Tipo": "Parboil",
        "Categoría": "Arroz",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/165472/ARROZ-DOS-HERMANOS-PARBOIL-1-7769.jpg?v=637665502412430000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1700",
        "Venta": "2550",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "28/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "30600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Salvador",
        "Tipo": "Tipo A",
        "Categoría": "Azúcar",
        "Imagen": "https://www.consumosbasicos.com.ar/images/000000000000051983731519.jpeg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "670",
        "Venta": "1010",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "01/12/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "12120",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Marolio",
        "Tipo": "Tipo A",
        "Categoría": "Azúcar",
        "Imagen": "https://http2.mlstatic.com/D_625068-MLA51742912883_092022-C.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "900",
        "Venta": "1350",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "13/08/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "16200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Azúcar",
        "Marca": "Azucel",
        "Tipo": "Tipo A",
        "Categoría": "Azúcar",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/325793/Azucar-Azucel-Comun-tipo-A-1-Kg-_1.jpg?v=638599585785670000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "1000g",
        "Costo": "900",
        "Venta": "1350",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "31/12/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "16200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Orégano",
        "Marca": "Las Elviras",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "https://especiaslaselviras.com/wp-content/uploads/2022/09/Oregano.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Ajo en polvo",
        "Marca": "Las Elviras",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "https://especiaslaselviras.com/wp-content/uploads/2022/09/Ajo-en-polvo.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Chimichurri",
        "Marca": "Las Elviras",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Adobo pizza",
        "Marca": "Las Elviras",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "25g",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "oct-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Comino",
        "Marca": "",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "ene-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Para Arroz",
        "Marca": "",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "oct-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bicarbonato",
        "Marca": "",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "20/01/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pimentón",
        "Marca": "",
        "Tipo": "",
        "Categoría": "Condimentos",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "ago-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "7200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Puré de tomates",
        "Marca": "S&P",
        "Tipo": "",
        "Categoría": "Conservas",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101971.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "520g",
        "Costo": "600",
        "Venta": "900",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "nov-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "10800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pulpa de tomate",
        "Marca": "Marolio",
        "Tipo": "",
        "Categoría": "Conservas",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_949300-MLA76508136660_052024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "520g",
        "Costo": "600",
        "Venta": "900",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "10800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Tomate triturado",
        "Marca": "S&P",
        "Tipo": "",
        "Categoría": "Conservas",
        "Imagen": "https://imagedelivery.net/olI9wp0b6luWFB9nPfnqjQ/res/abillionveg/image/upload/lgpu0e3ms7p6d7vrinfr/1598114874.jpg/public",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "970g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "27/04/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "21600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sardinas",
        "Marca": "Marbella",
        "Tipo": "En aceite",
        "Categoría": "Conservas",
        "Imagen": "https://elnenearg.vtexassets.com/arquivos/ids/165328/SARDINAS-MARBELLA-ACEITE-160GR-1-11301.jpg?v=638076657904300000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "160g",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "26/07/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "14400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Picadillo ",
        "Marca": "S&P",
        "Tipo": "Carne",
        "Categoría": "Conservas",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101930.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "90g",
        "Costo": "600",
        "Venta": "900",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "21/09/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "10800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Paté",
        "Marca": "S&P",
        "Tipo": "Foie",
        "Categoría": "Conservas",
        "Imagen": "https://www.vital.com.ar/wp-content/uploads/productos/101929.jpg?x49239",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "90g",
        "Costo": "600",
        "Venta": "900",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "22/07/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "10800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Atún",
        "Marca": "Bulnez",
        "Tipo": "Natural",
        "Categoría": "Conservas",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/542300/7791720003886_01.jpg?v=638568427419270000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "120g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "13/12/2026",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "28800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Puré de tomate",
        "Marca": "Sabores del Valle",
        "Tipo": "",
        "Categoría": "Conservas",
        "Imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/1/7/5/175d6eb3e0f6ccd481973d0dfbb7958d",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "500",
        "Venta": "750",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Arvejas",
        "Marca": "Molto",
        "Tipo": "Tetrabrik 1l",
        "Categoría": "Conservas",
        "Imagen": "https://dcdn.mitiendanube.com/stores/004/909/185/products/arvejas-molto-tetra-recart-340-gr-2ff358b98346b99af017218341180482-480-0.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "530",
        "Venta": "800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Edulcorante",
        "Marca": "Hileret ",
        "Tipo": "Mate",
        "Categoría": "Edulcorantes",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/200470/7790490998002_02.jpg?v=637550326133900000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "200ml",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "feb-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "28800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Galletitas de agua",
        "Marca": "Providencia ",
        "Tipo": "5 unidades",
        "Categoría": "Galletitas",
        "Imagen": "https://d1on8qs0xdu5jz.cloudfront.net/webapp/images/productos/b/0000011000/11659.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1210",
        "Venta": "1820",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochos",
        "Marca": "Don Satur",
        "Tipo": "Agridulce",
        "Categoría": "Galletitas",
        "Imagen": "https://www.donsatur.com.ar/wp-content/uploads/2024/01/02-bizcochos.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "630",
        "Venta": "950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochos",
        "Marca": "Don Satur",
        "Tipo": "Grasa",
        "Categoría": "Galletitas",
        "Imagen": "https://www.donsatur.com.ar/wp-content/uploads/2024/01/03-bizcochos.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "630",
        "Venta": "950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochos",
        "Marca": "9 de oro",
        "Tipo": "Agridulce",
        "Categoría": "Galletitas",
        "Imagen": "https://atencion24.ar/wp-content/uploads/2022/03/4ad5197a-aae7-44d0-8db9-4fb56c516745.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "500",
        "Venta": "750",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochos",
        "Marca": "9 de oro",
        "Tipo": "Salvado",
        "Categoría": "Galletitas",
        "Imagen": "https://www.argensend.com/wp-content/uploads/2021/09/D_NQ_NP_2X_688220-MLA44072217338_112020-F.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "600",
        "Venta": "900",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochos",
        "Marca": "9 de oro",
        "Tipo": "Clásicos",
        "Categoría": "Galletitas",
        "Imagen": "https://almacenfamily.com/productos/Bizcochos-De-Grasa-9-De-Oro-200-Gr.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "500",
        "Venta": "750",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pasta Dental",
        "Marca": "Colgate",
        "Tipo": "Familiar",
        "Categoría": "Higiene",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_20871cb36c5245b48bc9fa39978763c7_637592749684913593_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "70g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Máquina de afeitar",
        "Marca": "Gillette",
        "Tipo": "Triple (2 unids)",
        "Categoría": "Higiene",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/165/255/products/gillette-prestobarba-3-comfortgel-x2-maquinas-dc16df04d144540d1c17151824477588-1024-1024.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3200",
        "Venta": "4800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Pasta Dental",
        "Marca": "Odol",
        "Tipo": "Doble Protección",
        "Categoría": "Higiene",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_664727-MLU71000746978_082023-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3600",
        "Venta": "5400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Tipo": "Fuerza y brillo",
        "Categoría": "Higiene",
        "Imagen": "https://assets.unileversolutions.com/v1/88717149.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Tipo": "Hidratación y frizz control",
        "Categoría": "Higiene",
        "Imagen": "https://assets.unileversolutions.com/v1/92204219.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Tipo": "Regeneración y luminosidad",
        "Categoría": "Higiene",
        "Imagen": "https://assets.unileversolutions.com/v1/92203503.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Tipo": "Restauración y brillo",
        "Categoría": "Higiene",
        "Imagen": "https://assets.unileversolutions.com/v1/90142454.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo",
        "Marca": "Sedal",
        "Tipo": "Rizos definidos",
        "Categoría": "Higiene",
        "Imagen": "https://assets.unileversolutions.com/v1/88720623.png?im=AspectCrop=(985,985);Resize=(985,985)",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón de Tocador",
        "Marca": "Rexona",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_c0662ee45c01441ba2e602f817c3c6b8_638189398812017116_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Máquina de afeitar",
        "Marca": "Gillette",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://farmaciaslider.pe/my-assets/image/product/e7f4c860710f7df44fc069a77f12cb25.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Toallas femeninas",
        "Marca": "Kotex",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://media03.farmaciaslider.com.ar/33798-thickbox_default/kotex-esencial-con-alas-toallas-higienicas-normal-x-8.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_602605-MLA74792670662_032024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://www.farmaciassanchezantoniolli.com.ar/455-medium_default/shampoo-sedal-restauracion-instantanea-10ml.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Shampoo Sachet",
        "Marca": "Sedal",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_e180d3f5e90249c69e151b6b8fb92173_638502698936840708_0_m.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "400",
        "Venta": "600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Protectores Diarios",
        "Marca": "Doncella",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://cdn.batitienda.com/baticloud/images/product_picture_a1bf9fedcee64fd1bc1800df1f66cd0a_638599170607307417_0_m.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Protectores Diarios",
        "Marca": "Doncella",
        "Tipo": "",
        "Categoría": "Higiene",
        "Imagen": "https://www.centraloeste.com.ar/media/catalog/product/cache/ddb703dc084a33c8cde56cf551816b8e/7/7/7790940233264_-_protector_x_20_anatomico_con_deo_x_20.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Papel Higiénico",
        "Marca": "Grand Family",
        "Tipo": "6 rollos de 60m",
        "Categoría": "Higiene",
        "Imagen": "https://lh3.googleusercontent.com/proxy/kXlHrVIhjTOadOOxu4pcL0DaFEddbr4HRXryHNe6RgwRfoJO7UB7dAfhdDrJ1P360UAlIl7ojx4jKrPhdM41qSNR-H0yUXirdClmo8VmlUfz3x5ac6pw2lh6MoLhg-32aF4_anD91A",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1650",
        "Venta": "2480",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Papel Higiénico",
        "Marca": "Grand Family",
        "Tipo": "1 rollo de 60m",
        "Categoría": "Higiene",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/172/405/products/papel-higienico-90-mts1-9ff9eac5eb0e8dee3515998443889686-480-0.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "275",
        "Venta": "410",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón de Tocador",
        "Marca": "Limol",
        "Tipo": "3u x 90g",
        "Categoría": "Higiene",
        "Imagen": "https://cromochemical.com.ar/image/cache/catalog/Productos/Jab%C3%B3n%20en%20Pan/JATOLIM-1920x1080.webp",
        "Descripción": "3 unidades",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Protectores Diarios",
        "Marca": "Calipso",
        "Tipo": "Cola less 20u",
        "Categoría": "Higiene",
        "Imagen": "https://pedidosfarma.vtexassets.com/arquivos/ids/186327-800-auto?v=637696657985430000&width=800&height=auto&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "800",
        "Venta": "1200",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "Taragüí",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://modomarketar.vteximg.com.br/arquivos/ids/161974/Te-Taragui-S-ensobrar-X-25-Saq-1-6608.jpg?v=637879777592570000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "sep-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "25200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "La Virginia",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://www.lavirginia.com.ar/wp-content/uploads/2022/01/7790150211908_02-scaled.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "20/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "25200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té",
        "Marca": "Rosamonte",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://cordoba.parodisrl.com.ar/47211/te-rosamonte-25-saq-s-sobre.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "10/08/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "18000",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Mate cocido",
        "Marca": "Amanda",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://acdn.mitiendanube.com/stores/043/230/products/mate-cocido-tradicional_3_c1-86cb7d01479528ff5a16109958803054-1024-1024.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1500",
        "Venta": "2250",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "03/04/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "27000",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Té verde",
        "Marca": "Crysf",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://trapal.com.ar/media/cache/sylius_shop_product_thumbnail/66/50/f77f6183381d01dd8f01718f3ff5.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "700",
        "Venta": "1050",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Café ",
        "Marca": "La Virginia",
        "Tipo": "Torrado Clásico",
        "Categoría": "Infusiones",
        "Imagen": "https://www.lavirginia.com.ar/wp-content/uploads/2021/11/clasico-molido-torrado-1000.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2900",
        "Venta": "4350",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Mate cocido ",
        "Marca": "Duaren",
        "Tipo": "En saquitos",
        "Categoría": "Infusiones",
        "Imagen": "https://tienda.santamariasa.com.ar/comercio/images/a00059024.jpg",
        "Descripción": "25 saquitos",
        "Tamaño": "",
        "Peso": "",
        "Costo": "500",
        "Venta": "750",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por pack",
        "Marca": "Tang",
        "Tipo": "Naranja Mango",
        "Categoría": "Jugos",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/435018/7622201735371_E01.jpg?v=638400547833970000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3790",
        "Venta": "5690",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "25/09/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "68280",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por pack",
        "Marca": "Tang",
        "Tipo": "Naranja ",
        "Categoría": "Jugos",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/181368/Jugo-En-Polvo-Naranja-Durazno-Tang-15-Gr-1-15195.jpg?v=638403465881630000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3790",
        "Venta": "5690",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "17/10/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "68280",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por pack",
        "Marca": "Clight",
        "Tipo": "Naranja Dulce",
        "Categoría": "Jugos",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/322612/Jugo-En-Polvo-Clight-Naranja-Dulce-75-Gr-_1.jpg?v=638599545927670000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3790",
        "Venta": "5690",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "10/12/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "68280",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por pack",
        "Marca": "Clight",
        "Tipo": "Pomelo",
        "Categoría": "Jugos",
        "Imagen": "https://elnenearg.vtexassets.com/arquivos/ids/166087-800-auto?v=638104413709800000&width=800&height=auto&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "3790",
        "Venta": "5690",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "12/11/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "68280",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por unidad",
        "Marca": "Tang",
        "Tipo": "Naranja Mango",
        "Categoría": "Jugos",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/435018/7622201735371_E01.jpg?v=638400547833970000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "190",
        "Venta": "290",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "25/09/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "3480",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por unidad",
        "Marca": "Tang",
        "Tipo": "Naranja ",
        "Categoría": "Jugos",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/181368/Jugo-En-Polvo-Naranja-Durazno-Tang-15-Gr-1-15195.jpg?v=638403465881630000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "190",
        "Venta": "290",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "17/10/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "3480",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por unidad",
        "Marca": "Clight",
        "Tipo": "Naranja Dulce",
        "Categoría": "Jugos",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/322612/Jugo-En-Polvo-Clight-Naranja-Dulce-75-Gr-_1.jpg?v=638599545927670000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "190",
        "Venta": "290",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "10/12/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3480",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jugo por unidad",
        "Marca": "Clight",
        "Tipo": "Pomelo",
        "Categoría": "Jugos",
        "Imagen": "https://elnenearg.vtexassets.com/arquivos/ids/166087-800-auto?v=638104413709800000&width=800&height=auto&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "190",
        "Venta": "290",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "12/11/2024",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "3480",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Leche Entera",
        "Marca": "Verónica",
        "Tipo": "Tetrabrik 1l",
        "Categoría": "Leche",
        "Imagen": "https://hiperlibertad.vtexassets.com/arquivos/ids/167686/Leche-Entera-VERONICA-Larga-Vida-1-L-1-4720.jpg?v=637320610294900000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1360",
        "Venta": "2040",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Argentino",
        "Tipo": "2 unid",
        "Categoría": "Limpieza",
        "Imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/762004-800-600?v=638060457671000000&width=800&height=600&aspect=true",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "2400",
        "Venta": "3600",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Argentino",
        "Tipo": "1 unid",
        "Categoría": "Limpieza",
        "Imagen": "https://soysuper.com.ar/uploads/1565873489_MQ==.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Jabón Neutro",
        "Marca": "Villa Iris",
        "Tipo": "",
        "Categoría": "Limpieza",
        "Imagen": "https://distriflash.com.ar/wp-content/uploads/2018/11/1782-Jabon-blanco-V-I.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Detergente en barra",
        "Marca": "Villa Iris",
        "Tipo": "",
        "Categoría": "Limpieza",
        "Imagen": "https://dcdn.mitiendanube.com/stores/001/108/127/products/villa-iris-datergente-en-barra1-8e6fd721804488516c16664448613744-640-0.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Mermelada ",
        "Marca": "Marolio",
        "Tipo": "Durazno",
        "Categoría": "Mermeladas",
        "Imagen": "https://demo01.catalogoqr.ar/wp-content/uploads/2022/05/1031-MAROLIO-MERMELADA-DAMASCO-454-GR.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Mermelada ",
        "Marca": "Marolio",
        "Tipo": "Ciruela",
        "Categoría": "Mermeladas",
        "Imagen": "https://www.distribuidoralaflia.com.ar/wp-content/uploads/2020/09/MERMELADA-MAROLIO-LIGHT-X-390GR.jpeg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Lucchetti",
        "Tipo": "Codito",
        "Categoría": "Pastas",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/157/846/products/diseno-sin-titulo-2022-05-12t102428-9141-f88a149070c89a1fff16523619861162-1024-1024.png",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "17/08/2024",
        "Vence": "11/07/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "21600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Lucchetti",
        "Tipo": "Tirabuzón",
        "Categoría": "Pastas",
        "Imagen": "https://atencion24.ar/wp-content/uploads/2023/09/199a82aa-bd39-4853-8297-e0d3a701e277.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "17-ago",
        "Vence": "22/06/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "21600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Favorita",
        "Tipo": "Codito",
        "Categoría": "Pastas",
        "Imagen": "https://modomarketar.vteximg.com.br/arquivos/ids/171422/Fideos-Favorita-Codito-Hierro-X-500-G-1-41.jpg?v=638604561677670000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1100",
        "Venta": "1650",
        "Cantidad": "12",
        "Fecha": "17/08/2024",
        "Vence": "04/12/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "19800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Knorr",
        "Tipo": "Spaghetti",
        "Categoría": "Pastas",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/321949/Fideos-Knorr-Spaghetti-500-Gr-_2.jpg?v=638599537728700000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "17/08/2024",
        "Vence": "16/02/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "28800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos",
        "Marca": "Providencia",
        "Tipo": "Tagliatelle",
        "Categoría": "Pastas",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/178866/7798141971084_02.jpg?v=637468580608230000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "980",
        "Venta": "1470",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos ",
        "Marca": "Providencia ",
        "Tipo": "Tallarines",
        "Categoría": "Pastas",
        "Imagen": "https://statics.dinoonline.com.ar/imagenes/full_600x600_ma/2540829_f.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "980",
        "Venta": "1470",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos ",
        "Marca": "Providencia ",
        "Tipo": "Moños",
        "Categoría": "Pastas",
        "Imagen": "https://images.rappi.com.ar/products/1725905377274_8f300108-6e4b-40b1-b396-0aa8cfe58661_laprov.jpg",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "980",
        "Venta": "1470",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos ",
        "Marca": "Providencia ",
        "Tipo": "Nido",
        "Categoría": "Pastas",
        "Imagen": "https://saboreslaprovidencia.com.ar/wp-content/uploads/2020/04/nidotagliatelle500.png",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "980",
        "Venta": "1470",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Fideos ",
        "Marca": "Buen Gusto ",
        "Tipo": "Tallarines",
        "Categoría": "Pastas",
        "Imagen": "",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "1050",
        "Venta": "1580",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Polenta ",
        "Marca": "Presto Pronta",
        "Tipo": "",
        "Categoría": "Polenta",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/193158/7790580660000_01.jpg?v=637515950993770000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "",
        "Costo": "920",
        "Venta": "1380",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Bizcochuelo",
        "Marca": "Emeth",
        "Tipo": "Dulce de Leche",
        "Categoría": "Premezclas",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/410314/7791113005466_02.jpg?v=638345480717300000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "450g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "01/10/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "28800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Tipo": "Ananá",
        "Categoría": "Premezclas",
        "Imagen": "https://www.almacenencasa.com.ar/500-thickbox_default/gelatina-anana-vitaminizado-6-70-grs-emeth.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "nov-24",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "18720",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Tipo": "Cereza",
        "Categoría": "Premezclas",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/330352/Gelatina-Cereza-Vitaminizada-Emeth-70-GR-_1.jpg?v=638599648147970000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "18720",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Tipo": "Frambuesa",
        "Categoría": "Premezclas",
        "Imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/330349/Gelatina-Frambuesa-Con-Vitamina-Z-Emeth-70-Gr-_1.jpg?v=638599648096800000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "feb-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "18720",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Gelatina",
        "Marca": "Emeth",
        "Tipo": "Naranja",
        "Categoría": "Premezclas",
        "Imagen": "https://www.almacenencasa.com.ar/498-thickbox_default/gelatina-naranja-vitaminizado-6-70-grs-emeth.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "70g",
        "Costo": "1040",
        "Venta": "1560",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "ene-25",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "18720",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Dos Anclas",
        "Tipo": "Fina",
        "Categoría": "Sal",
        "Imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/188583/Sal-Fina-Dos-Anclas-X500gr-Sal-Fina-Dos-Anclas-Trilaminado-500-Gr-1-24926.jpg?v=636383496216030000",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "04/08/2023",
        "Estado": "Sin info",
        "Valores": "25200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Celusal",
        "Tipo": "Fina",
        "Categoría": "Sal",
        "Imagen": "https://acdn.mitiendanube.com/stores/001/193/620/products/1631-b3f7f78d649af51a2f16074500575515-480-0.jpg",
        "Descripción": "",
        "Tamaño": "Normal",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "15/07/2027",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "21600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Celusal",
        "Tipo": "Gruesa",
        "Categoría": "Sal",
        "Imagen": "https://arjosimarprod.vteximg.com.br/arquivos/ids/158813-1000-1000/Sal-Gruesa-Celusal-Paquete-1-kg-1-1768.jpg?v=637414118609900000",
        "Descripción": "",
        "Tamaño": "Grande",
        "Peso": "1000g",
        "Costo": "1800",
        "Venta": "2700",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "26/10/2027",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "32400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Sal",
        "Marca": "Dos Anclas",
        "Tipo": "Gruesa",
        "Categoría": "Sal",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/545896/7792900613017_02.jpg?v=638582149188200000",
        "Descripción": "",
        "Tamaño": "Grande",
        "Peso": "1000g",
        "Costo": "1700",
        "Venta": "2550",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "12/01/2023",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "30600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Cachamate",
        "Tipo": "Naranja",
        "Categoría": "Yerba",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/349845/7792280000285_01.jpg?v=638242443160200000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1400",
        "Venta": "2100",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "dic-24",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "25200",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Amanda",
        "Tipo": "Tradicional",
        "Categoría": "Yerba",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_832425-MLA48945377120_012022-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "250g",
        "Costo": "1000",
        "Venta": "1500",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "04/05/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "18000",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Salus",
        "Tipo": "Suave",
        "Categoría": "Yerba",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_694299-MLU78227074971_082024-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "27/03/2024",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "28800",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Nobleza Gaucha",
        "Tipo": "Selección",
        "Categoría": "Yerba",
        "Imagen": "https://carrefourar.vtexassets.com/arquivos/ids/206379/7790070507273_01.jpg?v=637611768560100000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1300",
        "Venta": "1950",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "20/07/2023",
        "Lote": "",
        "Estado": "Vencido",
        "Valores": "23400",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba",
        "Marca": "Cruz de Malta",
        "Tipo": "Tradicional, libre de gluten ",
        "Categoría": "Yerba",
        "Imagen": "https://http2.mlstatic.com/D_NQ_NP_837342-MLA71671213585_092023-O.webp",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1200",
        "Venta": "1800",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "08/03/2025",
        "Lote": "",
        "Estado": "En regla",
        "Valores": "21600",
        "_16": "",
        "_17": ""
    },
    {
        "Nombre": "Yerba ",
        "Marca": "Amanda",
        "Tipo": "Tradicional ",
        "Categoría": "Yerba",
        "Imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/161895/Yerba-Mate-sin-TACC-Amanda-500-Gr-1-1634.jpg?v=637473582678970000",
        "Descripción": "",
        "Tamaño": "",
        "Peso": "500g",
        "Costo": "1600",
        "Venta": "2400",
        "Cantidad": "12",
        "Fecha": "",
        "Vence": "",
        "Lote": "",
        "Estado": "",
        "Valores": "",
        "_16": "",
        "_17": ""
    }
]